// autogenerated by sql-generate v1.5.0 on Sun May 21 2017 02:49:39 GMT+0100 (WAT)

var sql = require('sql');


/**
 * SQL definition for Result.AcademicStaff
 */
exports.AcademicStaff = sql.define({
	name: 'AcademicStaff',
	columns: [
		{ name: 'id' },
		{ name: 'StaffId' },
		{ name: 'firstName' },
		{ name: 'lastName' },
		{ name: 'middleName' },
		{ name: 'password' },
		{ name: 'role' },
		{ name: 'departmentId' }
	]
});


/**
 * SQL definition for Result.Admin
 */
exports.Admin = sql.define({
	name: 'Admin',
	columns: [
		{ name: 'id' },
		{ name: 'userName' },
		{ name: 'firstName' },
		{ name: 'lastName' },
		{ name: 'middleName' },
		{ name: 'password' }
	]
});


/**
 * SQL definition for Result.Course
 */
exports.Course = sql.define({
	name: 'Course',
	columns: [
		{ name: 'id' },
		{ name: 'code' },
		{ name: 'title' },
		{ name: 'unit' },
		{ name: 'isCore' },
		{ name: 'isPrerequisite' },
		{ name: 'prerequisiteId' },
		{ name: 'coordinator' }
	]
});


/**
 * SQL definition for Result.Department
 */
exports.Department = sql.define({
	name: 'Department',
	columns: [
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'HOD' }
	]
});


/**
 * SQL definition for Result.DOM
 */
exports.DOM = sql.define({
	name: 'DOM',
	columns: [
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'departmentId' }
	]
});


/**
 * SQL definition for Result.Student
 */
exports.Student = sql.define({
	name: 'Student',
	columns: [
		{ name: 'id' },
		{ name: 'regNumber' },
		{ name: 'firstName' },
		{ name: 'lastName' },
		{ name: 'middleName' },
		{ name: 'password' },
		{ name: 'part' },
		{ name: 'departmentID' },
		{ name: 'domId' }
	]
});


/**
 * SQL definition for Result.StudentRegistedCourses
 */
exports.StudentRegistedCourses = sql.define({
	name: 'StudentRegistedCourses',
	columns: [
		{ name: 'id' },
		{ name: 'Student_id' },
		{ name: 'Student_departmentID' },
		{ name: 'Student_domId' },
		{ name: 'Course_id' },
		{ name: 'Course_coordinator' },
		{ name: 'grade' },
		{ name: 'testScore' },
		{ name: 'examScore' },
		{ name: 'totalScore' }
	]
});
